os: linux
dist: focal
language: perl
perl:
  - "5.30"

before_install:
  - "sudo apt-get update"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

script:
  - "make test"

notifications:
  email:
    on_failure: always
